sudo: required

language: node_js
node_js:
  - "10.11.0"

services:
  - docker

cache:
  directories:
    - node_modules

before_install:
  - npm prune

jobs:
  include:
    - stage: docker test
      script: docker-compose build
    - stage: deploy to production
      script: skip
      deploy:
        provider: heroku
        app: bguillaumat-dashboard
        api_key: $KEY
        on:
          node: "14.14.0"
          branch: master
    - stage: test production
      script: 'curl https://bguillaumat-dashboard.herokuapp.com'

